### ISSUE TITLE
scoop hook not working

### ISSUE THREAD

**Issue by boltomli** [winpax/sfsu#633]
## Describe the bug

Cannot use sfsu hook properly

## Steps to To Reproduce

```
Invoke-Expression (&sfsu hook)
scoop info test
```

## Expected behavior

```
No package found with the name "test"
```

## Full Output

```
error: the following required arguments were not provided:
  <PACKAGE>

Usage: sfsu.exe info <PACKAGE>
```

## Version

```
sfsu 1.10.1
sprinkles 1.10.1
branch:
commit_hash:e2aa6b9d
build_time:2024-04-15 14:09:32 +00:00
build_env:rustc 1.79.0-nightly (79424056b 2024-04-12),nightly-2024-04-13-x86_64-pc-windows-msvc
libgit2:1.7.2
```

## Additional context

```
Current Scoop version:
v0.3.1 - Released at 2022-11-15
```

**Comment by boltomli** [comment]
`.\target\debug\sfsu.exe hook --disable info`

```
thread 'main' panicked at src\commands.rs:79:36:
Invalid command name: info
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/79424056b05eaa9563d16dfab9b9a0c8f033f220/library\std\src\panicking.rs:645
   1: core::panicking::panic_fmt
             at /rustc/79424056b05eaa9563d16dfab9b9a0c8f033f220/library\core\src\panicking.rs:72
   2: sfsu::commands::impl$8::from
             at .\src\commands.rs:79
   3: clap_builder::builder::value_parser::via_prelude::impl$4::value_parser::closure$0<sfsu::commands::CommandsHooks>
             at C:\Users\lisong\scoop\persist\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\value_parser.rs:2555
   4: clap_builder::builder::value_parser::impl$52::parse_ref<clap_builder::builder::value_parser::StringValueParser,clap_builder::builder::value_parser::via_prelude::impl$4::value_parser::closure_env$0<sfsu::commands::CommandsHooks>,sfsu::commands::CommandsHoo
             at C:\Users\lisong\scoop\persist\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\value_parser.rs:2083
   5: clap_builder::builder::value_parser::TypedValueParser::parse_ref_<clap_builder::builder::value_parser::MapValueParser<clap_builder::builder::value_parser::StringValueParser,clap_builder::builder::value_parser::via_prelude::impl$4::value_parser::closure_en
             at C:\Users\lisong\scoop\persist\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\value_parser.rs:773
   6: clap_builder::builder::value_parser::impl$14::parse_ref_<sfsu::commands::CommandsHooks,clap_builder::builder::value_parser::MapValueParser<clap_builder::builder::value_parser::StringValueParser,clap_builder::builder::value_parser::via_prelude::impl$4::val
             at C:\Users\lisong\scoop\persist\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\value_parser.rs:658
   7: clap_builder::builder::value_parser::ValueParser::parse_ref
             at C:\Users\lisong\scoop\persist\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\value_parser.rs:242
   8: clap_builder::parser::parser::Parser::push_arg_values
             at C:\Users\lisong\scoop\persist\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\parser\parser.rs:1083
   9: clap_builder::parser::parser::Parser::react
             at C:\Users\lisong\scoop\persist\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\parser\parser.rs:1209
  10: clap_builder::parser::parser::Parser::resolve_pending
             at C:\Users\lisong\scoop\persist\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\parser\parser.rs:1102
  11: clap_builder::parser::parser::Parser::get_matches_with
             at C:\Users\lisong\scoop\persist\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\parser\parser.rs:477
  12: clap_builder::parser::parser::Parser::parse_subcommand
             at C:\Users\lisong\scoop\persist\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\parser\parser.rs:720
  13: clap_builder::parser::parser::Parser::get_matches_with
             at C:\Users\lisong\scoop\persist\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\parser\parser.rs:474
  14: clap_builder::builder::command::Command::_do_parse
             at C:\Users\lisong\scoop\persist\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\command.rs:4000
  15: clap_builder::builder::command::Command::try_get_matches_from_mut<std::env::ArgsOs,std::ffi::os_str::OsString>
             at C:\Users\lisong\scoop\persist\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\command.rs:830
  16: clap_builder::builder::command::Command::get_matches_from<std::env::ArgsOs,std::ffi::os_str::OsString>
             at C:\Users\lisong\scoop\persist\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\command.rs:701
  17: clap_builder::builder::command::Command::get_matches
             at C:\Users\lisong\scoop\persist\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\command.rs:610
  18: clap_builder::derive::Parser::parse<sfsu::Args>
             at C:\Users\lisong\scoop\persist\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\derive.rs:27
  19: sfsu::main
             at .\src\main.rs:81
  20: core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,anyhow::Error> > (*)(),tuple$<> >
             at /rustc/79424056b05eaa9563d16dfab9b9a0c8f033f220\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by boltomli** [comment]
`.\target\debug\sfsu.exe hook --disable info`

```
thread 'main' panicked at src\commands.rs:79:36:
Invalid command name: info
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/79424056b05eaa9563d16dfab9b9a0c8f033f220/library\std\src\panicking.rs:645
   1: core::panicking::panic_fmt
             at /rustc/79424056b05eaa9563d16dfab9b9a0c8f033f220/library\core\src\panicking.rs:72
   2: sfsu::commands::impl$8::from
             at .\src\commands.rs:79
   3: clap_builder::builder::value_parser::via_prelude::impl$4::value_parser::closure$0<sfsu::commands::CommandsHooks>
             at .cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\value_parser.rs:2555
   4: clap_builder::builder::value_parser::impl$52::parse_ref<clap_builder::builder::value_parser::StringValueParser,clap_builder::builder::value_parser::via_prelude::impl$4::value_parser::closure_env$0<sfsu::commands::CommandsHooks>,sfsu::commands::CommandsHoo
             at .cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\value_parser.rs:2083
   5: clap_builder::builder::value_parser::TypedValueParser::parse_ref_<clap_builder::builder::value_parser::MapValueParser<clap_builder::builder::value_parser::StringValueParser,clap_builder::builder::value_parser::via_prelude::impl$4::value_parser::closure_en
             at .cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\value_parser.rs:773
   6: clap_builder::builder::value_parser::impl$14::parse_ref_<sfsu::commands::CommandsHooks,clap_builder::builder::value_parser::MapValueParser<clap_builder::builder::value_parser::StringValueParser,clap_builder::builder::value_parser::via_prelude::impl$4::val
             at .cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\value_parser.rs:658
   7: clap_builder::builder::value_parser::ValueParser::parse_ref
             at .cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\value_parser.rs:242
   8: clap_builder::parser::parser::Parser::push_arg_values
             at .cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\parser\parser.rs:1083
   9: clap_builder::parser::parser::Parser::react
             at .cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\parser\parser.rs:1209
  10: clap_builder::parser::parser::Parser::resolve_pending
             at .cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\parser\parser.rs:1102
  11: clap_builder::parser::parser::Parser::get_matches_with
             at .cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\parser\parser.rs:477
  12: clap_builder::parser::parser::Parser::parse_subcommand
             at .cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\parser\parser.rs:720
  13: clap_builder::parser::parser::Parser::get_matches_with
             at .cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\parser\parser.rs:474
  14: clap_builder::builder::command::Command::_do_parse
             at .cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\command.rs:4000
  15: clap_builder::builder::command::Command::try_get_matches_from_mut<std::env::ArgsOs,std::ffi::os_str::OsString>
             at .cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\command.rs:830
  16: clap_builder::builder::command::Command::get_matches_from<std::env::ArgsOs,std::ffi::os_str::OsString>
             at .cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\command.rs:701
  17: clap_builder::builder::command::Command::get_matches
             at .cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\command.rs:610
  18: clap_builder::derive::Parser::parse<sfsu::Args>
             at .cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\derive.rs:27
  19: sfsu::main
             at .\src\main.rs:81
  20: core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,anyhow::Error> > (*)(),tuple$<> >
             at /rustc/79424056b05eaa9563d16dfab9b9a0c8f033f220\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jewlexx** [comment]
Thanks for reporting this, I'll work on fixing this ASAP.
