### ISSUE TITLE
Panic on `sfsu list`

### ISSUE THREAD

**Issue by brian6932** [winpax/sfsu#76]
**Describe the bug**
Happens every time for me

**Full Output**
<details>
  <summary>Panic</summary>
  
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `bucket`", line: 5, column: 1)', src/packages.rs:24:74
stack backtrace:
   0:     0x7ff795afe890 - std::backtrace_rs::backtrace::dbghelp::trace::h29c543a13337066e
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\..\..\backtrace\src\backtrace/dbghelp.rs:98:5
   1:     0x7ff795afe890 - std::backtrace_rs::backtrace::trace_unsynchronized::h4735bf1454f795a4
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\..\..\backtrace\src\backtrace/mod.rs:66:5
   2:     0x7ff795afe890 - std::sys_common::backtrace::_print_fmt::hcb654bc1a0abc766
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\sys_common/backtrace.rs:65:5
   3:     0x7ff795afe890 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h57d91a764bda489c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\sys_common/backtrace.rs:44:22
   4:     0x7ff795b57b3b - core::fmt::write::hbb11da7029f1c3d7
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\core\src\fmt/mod.rs:1209:17
   5:     0x7ff795af0c25 - std::io::Write::write_fmt::h2715f7121e6ec555
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\io/mod.rs:1682:15
   6:     0x7ff795afe5e4 - std::sys_common::backtrace::_print::h34a1cbe62da2dce8
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\sys_common/backtrace.rs:47:5
   7:     0x7ff795afe5e4 - std::sys_common::backtrace::print::h8e105c6f4128fa25
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\sys_common/backtrace.rs:34:9
   8:     0x7ff795b019af - std::panicking::default_hook::{{closure}}::h8578e99717a9b436
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src/panicking.rs:267:22
   9:     0x7ff795b016b7 - std::panicking::default_hook::h811108f7b9376e24
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src/panicking.rs:286:9
  10:     0x7ff795b022df - std::panicking::rust_panic_with_hook::hb34f0407887ca1d1
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src/panicking.rs:688:13
  11:     0x7ff795b02055 - std::panicking::begin_panic_handler::{{closure}}::h92b5222c88a2dda2
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src/panicking.rs:579:13
  12:     0x7ff795aff3cf - std::sys_common::backtrace::__rust_end_short_backtrace::h66b1044e4311a43f
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\sys_common/backtrace.rs:137:18
  13:     0x7ff795b01d70 - rust_begin_unwind
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src/panicking.rs:575:5
  14:     0x7ff795b543c5 - core::panicking::panic_fmt::h22ee573cfcae3983
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\core\src/panicking.rs:65:14
  15:     0x7ff795b54993 - core::result::unwrap_failed::hc39515d7b13f74e4
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\core\src/result.rs:1791:5
  16:     0x7ff795973041 - sfsu::packages::FromPath::from_path::h812eef12f1c10f99
  17:     0x7ff79596997b - <sfsu::commands::list::Args as sfsu::commands::Command>::run::{{closure}}::h27f875c27d2933d3
  18:     0x7ff795962cb3 - rayon::iter::plumbing::bridge_producer_consumer::helper::hd464608e38019d1e
  19:     0x7ff795952948 - rayon_core::join::join_context::{{closure}}::h8857a7079712e28b
  20:     0x7ff795962fd7 - rayon::iter::plumbing::bridge_producer_consumer::helper::hd464608e38019d1e
  21:     0x7ff795952a33 - rayon_core::join::join_context::{{closure}}::h8857a7079712e28b
  22:     0x7ff795962fd7 - rayon::iter::plumbing::bridge_producer_consumer::helper::hd464608e38019d1e
  23:     0x7ff795952948 - rayon_core::join::join_context::{{closure}}::h8857a7079712e28b
  24:     0x7ff795962fd7 - rayon::iter::plumbing::bridge_producer_consumer::helper::hd464608e38019d1e
  25:     0x7ff795952948 - rayon_core::join::join_context::{{closure}}::h8857a7079712e28b
  26:     0x7ff795962fd7 - rayon::iter::plumbing::bridge_producer_consumer::helper::hd464608e38019d1e
  27:     0x7ff795966220 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h0686b1f2c2a79f0b
  28:     0x7ff795a5da95 - rayon_core::registry::WorkerThread::wait_until_cold::hfc7024374a3ba675
  29:     0x7ff795a5aa59 - rayon_core::registry::ThreadBuilder::run::hcf54c1bb1402223d
  30:     0x7ff795a56972 - std::sys_common::backtrace::__rust_begin_short_backtrace::h09ce8ec31001c67d
  31:     0x7ff795a5775e - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc301799b5e84498d
  32:     0x7ff795b12107 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hdbc2fb0b40a7217d
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\alloc\src/boxed.rs:1987:9
  33:     0x7ff795b12107 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h21b2899e81d2a952
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\alloc\src/boxed.rs:1987:9
  34:     0x7ff795b12107 - std::sys::windows::thread::Thread::new::thread_start::h35d0d46d3ec957a3
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\sys\windows/thread.rs:56:17
  35:     0x7fff4e90117e - <unknown>
  36:     0x7fff4f6e42db - <unknown>
```

</details>

**sfsu 1.4.0**

**Additional context**

**Comment by jewlexx** [comment]
Could you attach the source manifest file?
I, and should add a special case for panics like this, but it would be good to know the source of the problem as well.

**Comment by jewlexx** [comment]
This has been fixed in the latest release, but I will leave the issue open, as it would be better to have an edge case that supports those manifest types rather than just saying "Invalid".
If you are able to provide the manifest that would be much appreciated.

**Comment by brian6932** [comment]
> Could you attach the source manifest file?

Uhh I'm not sure which package caused this issue, on normal `(scoop list).Source`, all packages have a normal looking repo. So since I don't know [I'll just send a `scoop export`](https://i.alienpls.org/Ymj.json)

**Comment by jewlexx** [comment]
The manifest(s) should now have "Invalid" or and empty string in place of the bucket & version properties, if that helps you find it. I can't seem to find anything wrong in the `scoop export` so I'm not too sure what is wrong.

**Comment by brian6932** [comment]
![image](https://user-images.githubusercontent.com/18603393/215099357-87c499f4-6441-4954-88a2-92382d1aa95b.png)
Ah it was the version generated obs-studio package

**Comment by jewlexx** [comment]
1. How does that happen? Like where did that manifest come from?
2. Would you be able to attach a copy of that manifest?

**Comment by brian6932** [comment]
> 1\. How does that happen? Like where did that manifest come from?

Yes, it's just a generated manifest for a specific version, like this: https://github.com/ScoopInstaller/Scoop/issues/3045#issuecomment-1138042773 `scoop install package@version`

> 2\. Would you be able to attach a copy of that manifest?

```json
{
    "version": "27.2.4",
    "description": "Video recording and live streaming software",
    "homepage": "https://obsproject.com",
    "license": "GPL-2.0-only",
    "notes": [
        "Add Virtual Camera module by running: \"$dir\\data\\obs-plugins\\win-dshow\\virtualcam-install.bat\"",
        "Remove it by running: \"$dir\\data\\obs-plugins\\win-dshow\\virtualcam-uninstall.bat\""
    ],
    "architecture": {
        "64bit": {
            "url": "https://cdn-fastly.obsproject.com/downloads/OBS-Studio-27.2.4-Full-x64.zip",
            "hash": "fae9840096c43a62b410d91985b4b5fdd5b0d6e8d54ef4afe7af47180da8ae21",
            "shortcuts": [
                [
                    "bin\\64bit\\obs64.exe",
                    "OBS Studio"
                ]
            ]
        }
    },
    "pre_install": "if (!(Test-Path \"$persist_dir\\portable_mode.txt\")) { New-Item \"$dir\\portable_mode.txt\" | Out-Null }",
    "persist": [
        "config",
        "portable_mode.txt"
    ],
    "checkver": {
        "url": "https://obsproject.com/download",
        "regex": "OBS-Studio-([\\d.]+)-Full-x64\\.zip"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://cdn-fastly.obsproject.com/downloads/OBS-Studio-$version-Full-x64.zip"
            }
        }
    }
}
```

Basically the same thing that happened here: https://github.com/jewlexx/sfsu/issues/12

**Comment by jewlexx** [comment]
Ah, I didn't realise that was possible in Scoop. Thanks for your help, I'll work on supporting this, rather than just having it say "Invalid"
